# Generated by Django 6.1 on 2026-08-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='status',
        ),
    ]
