# Generated by Django 6.1 on 2026-08-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_workout_finished_at_remove_workout_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='weight_description',
        ),
    ]
