# Generated by Django 6.1 on 2026-08-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_exerciseset_weight_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['expires_at'],
            },
        ),
    ]
