# Generated by Django 6.1 on 2026-08-17 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_empty_workouts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPresetExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('name',), name='unique_system_exercise_name'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('user__isnull', False)), fields=('user', 'name'), name='unique_active_custom_exercise_name_per_user'),
        ),
        migrations.AddField(
            model_name='workoutpreset',
            name='muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_presets', to='core.musclegroup'),
        ),
        migrations.AddField(
            model_name='workoutpreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutpresetexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preset_entries', to='core.exercise'),
        ),
        migrations.AddField(
            model_name='workoutpresetexercise',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_entries', to='core.workoutpreset'),
        ),
        migrations.AddField(
            model_name='workoutpreset',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_presets', through='core.WorkoutPresetExercise', to='core.exercise'),
        ),
        migrations.AddConstraint(
            model_name='workoutpresetexercise',
            constraint=models.UniqueConstraint(fields=('preset', 'exercise'), name='unique_exercise_per_workout_preset'),
        ),
        migrations.AddConstraint(
            model_name='workoutpresetexercise',
            constraint=models.UniqueConstraint(fields=('preset', 'order'), name='unique_exercise_order_per_workout_preset'),
        ),
        migrations.AddConstraint(
            model_name='workoutpreset',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_workout_preset_name_per_user'),
        ),
    ]
